### ISSUE TITLE
unknown_error   linuxmint17

### ISSUE THREAD

**Issue by gothack329** [im-qq/iqq#16]
10:18:09.388 [I/O dispatcher 2] DEBUG org.apache.http.headers - http-outgoing-2 << Set-Cookie: ptisp=; PATH=/; DOMAIN=qq.com;
10:18:09.388 [I/O dispatcher 2] DEBUG o.a.h.n.p.HttpAsyncRequestExecutor - http-outgoing-2 [ACTIVE(171)] Response received
10:18:09.388 [I/O dispatcher 2] DEBUG o.a.h.i.n.c.DefaultHttpAsyncClient - [exchange: 2] Response received HTTP/1.1 200 OK
10:18:09.388 [I/O dispatcher 2] DEBUG iqq.im.http.QQHttpCookieJar - [New Cookie] Cookie [name=confirmuin, value=0, domain=ptlogin2.qq.com, path=/, expired=null]
10:18:09.388 [I/O dispatcher 2] DEBUG iqq.im.http.QQHttpCookieJar - [New Cookie] Cookie [name=ptvfsession, value=5ba701c11e03f4a2d6972b34d6e8d5ce5d7fed0de1636e117d19bf8d58d4d4534e7a6e73993c8bf960d86f178d05fab7, domain=ptlogin2.qq.com, path=/, expired=null]
10:18:09.388 [I/O dispatcher 2] DEBUG iqq.im.http.QQHttpCookieJar - [New Cookie] Cookie [name=ptisp, value=, domain=qq.com, path=/, expired=null]
10:18:09.389 [I/O dispatcher 2] DEBUG o.a.h.c.p.ResponseProcessCookies - Cookie accepted: "[version: 0][name: confirmuin][value: 0][domain: ptlogin2.qq.com][path: /][expiry: null]". 
10:18:09.389 [I/O dispatcher 2] DEBUG o.a.h.c.p.ResponseProcessCookies - Cookie accepted: "[version: 0][name: ptvfsession][value: 5ba701c11e03f4a2d6972b34d6e8d5ce5d7fed0de1636e117d19bf8d58d4d4534e7a6e73993c8bf960d86f178d05fab7][domain: ptlogin2.qq.com][path: /][expiry: null]". 
10:18:09.389 [I/O dispatcher 2] DEBUG o.a.h.c.p.ResponseProcessCookies - Cookie accepted: "[version: 0][name: ptisp][value: ][domain: qq.com][path: /][expiry: null]". 
10:18:09.389 [I/O dispatcher 2] DEBUG o.a.h.n.p.HttpAsyncRequestExecutor - http-outgoing-2 [ACTIVE(171)] Input ready
10:18:09.389 [I/O dispatcher 2] DEBUG o.a.h.i.n.c.DefaultHttpAsyncClient - [exchange: 2] Consume content
10:18:09.389 [I/O dispatcher 2] DEBUG o.a.h.nio.reactor.ssl.SSLIOSession - http-outgoing-2 10.12.209.67:53435<->112.90.140.233:443[ACTIVE][r:r][ACTIVE][NOT_HANDSHAKING][0][0][0][0]: 0 bytes read
10:18:09.389 [I/O dispatcher 2] DEBUG o.a.h.nio.reactor.ssl.SSLIOSession - http-outgoing-2 10.12.209.67:53435<->112.90.140.233:443[ACTIVE][r:r][ACTIVE][NOT_HANDSHAKING][0][0][0][0]: 0 bytes read
10:18:09.389 [I/O dispatcher 2] DEBUG o.a.h.nio.reactor.ssl.SSLIOSession - http-outgoing-2 10.12.209.67:53435<->112.90.140.233:443[ACTIVE][r:r][ACTIVE][NOT_HANDSHAKING][0][0][0][0]: 0 bytes read
10:18:09.390 [I/O dispatcher 2] DEBUG o.a.h.i.n.c.DefaultHttpAsyncClient - [exchange: 2] Response fully read
10:18:09.390 [I/O dispatcher 2] DEBUG o.a.h.i.n.c.DefaultHttpAsyncClient - [exchange: 2] Connection can be kept alive indefinitely
10:18:09.390 [I/O dispatcher 2] DEBUG o.a.h.i.n.c.DefaultHttpAsyncClient - [exchange: 2] Response processed
10:18:09.390 [AWT-EventQueue-0] DEBUG iqq.im.action.AbstractHttpAction - application/x-javascript; charset=utf-8
10:18:09.390 [I/O dispatcher 2] DEBUG o.a.h.i.n.c.DefaultHttpAsyncClient - [exchange: 2] releasing connection [id:2][route:{s}->https://ssl.ptlogin2.qq.com][state:null]
10:18:09.390 [I/O dispatcher 2] DEBUG o.a.h.nio.reactor.ssl.SSLIOSession - http-outgoing-2 10.12.209.67:53435<->112.90.140.233:443[ACTIVE][r:r][ACTIVE][NOT_HANDSHAKING][0][0][0][0]: Remove attribute http.nio.exchange-handler
10:18:09.390 [I/O dispatcher 2] DEBUG o.a.h.i.n.c.PoolingClientAsyncConnectionManager - Connection released: [id: 2][route: {s}->https://ssl.ptlogin2.qq.com][total kept alive: 2; route allocated: 1 of 2; total allocated: 2 of 20]
10:18:09.390 [I/O dispatcher 2] DEBUG o.a.h.n.p.HttpAsyncRequestExecutor - http-outgoing-2 [ACTIVE] [chunk-coded; completed: true]
10:18:09.391 [AWT-EventQueue-0] DEBUG i.a.service.impl.IMEventServiceImpl - Broadcast IMEvent: LOGIN_ERROR, listeners: 1
10:18:09.391 [AWT-EventQueue-0] INFO  iqq.app.ui.module.UILoginModule - login error......UNKNOWN_ERROR
10:18:12.894 [AWT-EventQueue-0] WARN  iqq.app.module.QQLogicModule - Login Error!!
iqq.im.QQException: UNKNOWN_ERROR
    at iqq.im.action.AbstractHttpAction.onHttpFinish(AbstractHttpAction.java:94) [IQQ-1.0-nightly.jar:na]
    at iqq.im.actor.HttpActor.execute(HttpActor.java:76) [IQQ-1.0-nightly.jar:na]
    at iqq.im.actor.SwingActorDispatcher$1.run(SwingActorDispatcher.java:49) [IQQ-1.0-nightly.jar:na]
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:251) [na:1.7.0_55]
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733) [na:1.7.0_55]
    at java.awt.EventQueue.access$200(EventQueue.java:103) [na:1.7.0_55]
    at java.awt.EventQueue$3.run(EventQueue.java:694) [na:1.7.0_55]
    at java.awt.EventQueue$3.run(EventQueue.java:692) [na:1.7.0_55]
    at java.security.AccessController.doPrivileged(Native Method) [na:1.7.0_55]
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76) [na:1.7.0_55]
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:703) [na:1.7.0_55]
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242) [na:1.7.0_55]
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161) [na:1.7.0_55]
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150) [na:1.7.0_55]
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146) [na:1.7.0_55]
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138) [na:1.7.0_55]
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91) [na:1.7.0_55]
Caused by: java.lang.NumberFormatException: For input string: "00000000108bb2cc', '5ba701c11e03f4a2d6972b34d6e8d5ce5d7fed0de1636e117d19bf8d58d4d4534e7a6e73993c8bf960d86f178d05fab7"
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[na:1.7.0_55]
    at java.lang.Long.parseLong(Long.java:441) ~[na:1.7.0_55]
    at iqq.im.action.CheckVerifyAction.onHttpStatusOK(CheckVerifyAction.java:65) ~[IQQ-1.0-nightly.jar:na]
    at iqq.im.action.AbstractHttpAction.onHttpFinish(AbstractHttpAction.java:85) [IQQ-1.0-nightly.jar:na]
    ... 16 common frames omitted
登录出现unknown error

**Comment by blusewang** [comment]
ubuntu 14.04 login unkown_error

**Comment by liangjs** [comment]
+10086
